// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // URL directe, pas celle de l'app : le verrou posé par les migrations
    // n'est pas compatible avec le pooler de connexions Neon (PgBouncer), et
    // provoque un timeout P1002 sinon.
    url: process.env["DIRECT_URL"],
  },
});
